controller_frequency: 10.0
planner_frequency: 5.0
base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"
oscillation_timeout: 10.0
oscillation_distance: 0.2
clearing_rotation_allowed: true
recovery_behavior_enabled: true
