// Generated by gencpp from file postbot/BallInfo.msg
// DO NOT EDIT!


#ifndef POSTBOT_MESSAGE_BALLINFO_H
#define POSTBOT_MESSAGE_BALLINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace postbot
{
template <class ContainerAllocator>
struct BallInfo_
{
  typedef BallInfo_<ContainerAllocator> Type;

  BallInfo_()
    : color()
    , x(0.0)
    , y(0.0)  {
    }
  BallInfo_(const ContainerAllocator& _alloc)
    : color(_alloc)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::postbot::BallInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::postbot::BallInfo_<ContainerAllocator> const> ConstPtr;

}; // struct BallInfo_

typedef ::postbot::BallInfo_<std::allocator<void> > BallInfo;

typedef boost::shared_ptr< ::postbot::BallInfo > BallInfoPtr;
typedef boost::shared_ptr< ::postbot::BallInfo const> BallInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::postbot::BallInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::postbot::BallInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::postbot::BallInfo_<ContainerAllocator1> & lhs, const ::postbot::BallInfo_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::postbot::BallInfo_<ContainerAllocator1> & lhs, const ::postbot::BallInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace postbot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::postbot::BallInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::postbot::BallInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::postbot::BallInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::postbot::BallInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::postbot::BallInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::postbot::BallInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::postbot::BallInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eab6da5b2968819e8b305355e8d814c";
  }

  static const char* value(const ::postbot::BallInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eab6da5b2968819ULL;
  static const uint64_t static_value2 = 0xe8b305355e8d814cULL;
};

template<class ContainerAllocator>
struct DataType< ::postbot::BallInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "postbot/BallInfo";
  }

  static const char* value(const ::postbot::BallInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::postbot::BallInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::postbot::BallInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::postbot::BallInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BallInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::postbot::BallInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::postbot::BallInfo_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSTBOT_MESSAGE_BALLINFO_H
