// Generated by gencpp from file postbot/reset_boxesResponse.msg
// DO NOT EDIT!


#ifndef POSTBOT_MESSAGE_RESET_BOXESRESPONSE_H
#define POSTBOT_MESSAGE_RESET_BOXESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace postbot
{
template <class ContainerAllocator>
struct reset_boxesResponse_
{
  typedef reset_boxesResponse_<ContainerAllocator> Type;

  reset_boxesResponse_()
    : done(false)  {
    }
  reset_boxesResponse_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::postbot::reset_boxesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::postbot::reset_boxesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct reset_boxesResponse_

typedef ::postbot::reset_boxesResponse_<std::allocator<void> > reset_boxesResponse;

typedef boost::shared_ptr< ::postbot::reset_boxesResponse > reset_boxesResponsePtr;
typedef boost::shared_ptr< ::postbot::reset_boxesResponse const> reset_boxesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::postbot::reset_boxesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::postbot::reset_boxesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::postbot::reset_boxesResponse_<ContainerAllocator1> & lhs, const ::postbot::reset_boxesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::postbot::reset_boxesResponse_<ContainerAllocator1> & lhs, const ::postbot::reset_boxesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace postbot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::postbot::reset_boxesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::postbot::reset_boxesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::postbot::reset_boxesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::postbot::reset_boxesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::postbot::reset_boxesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::postbot::reset_boxesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::postbot::reset_boxesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::postbot::reset_boxesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::postbot::reset_boxesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "postbot/reset_boxesResponse";
  }

  static const char* value(const ::postbot::reset_boxesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::postbot::reset_boxesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n"
;
  }

  static const char* value(const ::postbot::reset_boxesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::postbot::reset_boxesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reset_boxesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::postbot::reset_boxesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::postbot::reset_boxesResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSTBOT_MESSAGE_RESET_BOXESRESPONSE_H
