// Generated by gencpp from file postbot/reset_boxesRequest.msg
// DO NOT EDIT!


#ifndef POSTBOT_MESSAGE_RESET_BOXESREQUEST_H
#define POSTBOT_MESSAGE_RESET_BOXESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace postbot
{
template <class ContainerAllocator>
struct reset_boxesRequest_
{
  typedef reset_boxesRequest_<ContainerAllocator> Type;

  reset_boxesRequest_()
    {
    }
  reset_boxesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::postbot::reset_boxesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::postbot::reset_boxesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct reset_boxesRequest_

typedef ::postbot::reset_boxesRequest_<std::allocator<void> > reset_boxesRequest;

typedef boost::shared_ptr< ::postbot::reset_boxesRequest > reset_boxesRequestPtr;
typedef boost::shared_ptr< ::postbot::reset_boxesRequest const> reset_boxesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::postbot::reset_boxesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::postbot::reset_boxesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace postbot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::postbot::reset_boxesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::postbot::reset_boxesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::postbot::reset_boxesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::postbot::reset_boxesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::postbot::reset_boxesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::postbot::reset_boxesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::postbot::reset_boxesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::postbot::reset_boxesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::postbot::reset_boxesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "postbot/reset_boxesRequest";
  }

  static const char* value(const ::postbot::reset_boxesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::postbot::reset_boxesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::postbot::reset_boxesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::postbot::reset_boxesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reset_boxesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::postbot::reset_boxesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::postbot::reset_boxesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // POSTBOT_MESSAGE_RESET_BOXESREQUEST_H
