// Generated by gencpp from file postbot/reset_boxes.msg
// DO NOT EDIT!


#ifndef POSTBOT_MESSAGE_RESET_BOXES_H
#define POSTBOT_MESSAGE_RESET_BOXES_H

#include <ros/service_traits.h>


#include <postbot/reset_boxesRequest.h>
#include <postbot/reset_boxesResponse.h>


namespace postbot
{

struct reset_boxes
{

typedef reset_boxesRequest Request;
typedef reset_boxesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset_boxes
} // namespace postbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::postbot::reset_boxes > {
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::postbot::reset_boxes&) { return value(); }
};

template<>
struct DataType< ::postbot::reset_boxes > {
  static const char* value()
  {
    return "postbot/reset_boxes";
  }

  static const char* value(const ::postbot::reset_boxes&) { return value(); }
};


// service_traits::MD5Sum< ::postbot::reset_boxesRequest> should match
// service_traits::MD5Sum< ::postbot::reset_boxes >
template<>
struct MD5Sum< ::postbot::reset_boxesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::postbot::reset_boxes >::value();
  }
  static const char* value(const ::postbot::reset_boxesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::postbot::reset_boxesRequest> should match
// service_traits::DataType< ::postbot::reset_boxes >
template<>
struct DataType< ::postbot::reset_boxesRequest>
{
  static const char* value()
  {
    return DataType< ::postbot::reset_boxes >::value();
  }
  static const char* value(const ::postbot::reset_boxesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::postbot::reset_boxesResponse> should match
// service_traits::MD5Sum< ::postbot::reset_boxes >
template<>
struct MD5Sum< ::postbot::reset_boxesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::postbot::reset_boxes >::value();
  }
  static const char* value(const ::postbot::reset_boxesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::postbot::reset_boxesResponse> should match
// service_traits::DataType< ::postbot::reset_boxes >
template<>
struct DataType< ::postbot::reset_boxesResponse>
{
  static const char* value()
  {
    return DataType< ::postbot::reset_boxes >::value();
  }
  static const char* value(const ::postbot::reset_boxesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSTBOT_MESSAGE_RESET_BOXES_H
