// Generated by gencpp from file postbot/spawn_ball.msg
// DO NOT EDIT!


#ifndef POSTBOT_MESSAGE_SPAWN_BALL_H
#define POSTBOT_MESSAGE_SPAWN_BALL_H

#include <ros/service_traits.h>


#include <postbot/spawn_ballRequest.h>
#include <postbot/spawn_ballResponse.h>


namespace postbot
{

struct spawn_ball
{

typedef spawn_ballRequest Request;
typedef spawn_ballResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct spawn_ball
} // namespace postbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::postbot::spawn_ball > {
  static const char* value()
  {
    return "3b23249ad591553cd39c3c9bc459fc3d";
  }

  static const char* value(const ::postbot::spawn_ball&) { return value(); }
};

template<>
struct DataType< ::postbot::spawn_ball > {
  static const char* value()
  {
    return "postbot/spawn_ball";
  }

  static const char* value(const ::postbot::spawn_ball&) { return value(); }
};


// service_traits::MD5Sum< ::postbot::spawn_ballRequest> should match
// service_traits::MD5Sum< ::postbot::spawn_ball >
template<>
struct MD5Sum< ::postbot::spawn_ballRequest>
{
  static const char* value()
  {
    return MD5Sum< ::postbot::spawn_ball >::value();
  }
  static const char* value(const ::postbot::spawn_ballRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::postbot::spawn_ballRequest> should match
// service_traits::DataType< ::postbot::spawn_ball >
template<>
struct DataType< ::postbot::spawn_ballRequest>
{
  static const char* value()
  {
    return DataType< ::postbot::spawn_ball >::value();
  }
  static const char* value(const ::postbot::spawn_ballRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::postbot::spawn_ballResponse> should match
// service_traits::MD5Sum< ::postbot::spawn_ball >
template<>
struct MD5Sum< ::postbot::spawn_ballResponse>
{
  static const char* value()
  {
    return MD5Sum< ::postbot::spawn_ball >::value();
  }
  static const char* value(const ::postbot::spawn_ballResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::postbot::spawn_ballResponse> should match
// service_traits::DataType< ::postbot::spawn_ball >
template<>
struct DataType< ::postbot::spawn_ballResponse>
{
  static const char* value()
  {
    return DataType< ::postbot::spawn_ball >::value();
  }
  static const char* value(const ::postbot::spawn_ballResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSTBOT_MESSAGE_SPAWN_BALL_H
