// Generated by gencpp from file postbot/spawn_ballRequest.msg
// DO NOT EDIT!


#ifndef POSTBOT_MESSAGE_SPAWN_BALLREQUEST_H
#define POSTBOT_MESSAGE_SPAWN_BALLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace postbot
{
template <class ContainerAllocator>
struct spawn_ballRequest_
{
  typedef spawn_ballRequest_<ContainerAllocator> Type;

  spawn_ballRequest_()
    : x(0.0)
    , y(0.0)
    , color()  {
    }
  spawn_ballRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::postbot::spawn_ballRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::postbot::spawn_ballRequest_<ContainerAllocator> const> ConstPtr;

}; // struct spawn_ballRequest_

typedef ::postbot::spawn_ballRequest_<std::allocator<void> > spawn_ballRequest;

typedef boost::shared_ptr< ::postbot::spawn_ballRequest > spawn_ballRequestPtr;
typedef boost::shared_ptr< ::postbot::spawn_ballRequest const> spawn_ballRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::postbot::spawn_ballRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::postbot::spawn_ballRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::postbot::spawn_ballRequest_<ContainerAllocator1> & lhs, const ::postbot::spawn_ballRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::postbot::spawn_ballRequest_<ContainerAllocator1> & lhs, const ::postbot::spawn_ballRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace postbot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::postbot::spawn_ballRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::postbot::spawn_ballRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::postbot::spawn_ballRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::postbot::spawn_ballRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::postbot::spawn_ballRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::postbot::spawn_ballRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::postbot::spawn_ballRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c03abd5fc1a3340a9a66fb478def5f1b";
  }

  static const char* value(const ::postbot::spawn_ballRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc03abd5fc1a3340aULL;
  static const uint64_t static_value2 = 0x9a66fb478def5f1bULL;
};

template<class ContainerAllocator>
struct DataType< ::postbot::spawn_ballRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "postbot/spawn_ballRequest";
  }

  static const char* value(const ::postbot::spawn_ballRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::postbot::spawn_ballRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"string color\n"
;
  }

  static const char* value(const ::postbot::spawn_ballRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::postbot::spawn_ballRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct spawn_ballRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::postbot::spawn_ballRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::postbot::spawn_ballRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSTBOT_MESSAGE_SPAWN_BALLREQUEST_H
