(cl:defpackage postbot-srv
  (:use )
  (:export
   "RESET_BOXES"
   "<RESET_BOXES-REQUEST>"
   "RESET_BOXES-REQUEST"
   "<RESET_BOXES-RESPONSE>"
   "RESET_BOXES-RESPONSE"
   "SPAWN_BALL"
   "<SPAWN_BALL-REQUEST>"
   "SPAWN_BALL-REQUEST"
   "<SPAWN_BALL-RESPONSE>"
   "SPAWN_BALL-RESPONSE"
  ))

